### ISSUE TITLE
Missing Packages in Conda Installation

### ISSUE THREAD

**Issue by AndrewHerzing** [hyperspy/hyperspy_gui_ipywidgets#57]
When Hyperspy and the GUI widgets are installed via pip:

```
pip install hyperspy[gui-jupyter]
```

the `ipympl` package is included in the installation.  However, when installing with Conda:

```
conda install -c conda-forge hyperspy-base hyperspy-gui-ipywidgets
```

`ipympl` is missing. Since the latter is required for proper plotting of the widgets in Jupyter, presumably it should be included.

**Comment by ericpre** [comment]
The equivalent of
```
conda install -c conda-forge hyperspy-base hyperspy-gui-ipywidgets
```

in pip would be
```
pip install hyperspy hyperspy-gui-ipywidgets
```

and will not install `ipympl` and both are consistent.
`hyperspy_gui_ipywidgets` doesn't depends on `ipympl` and doesn't need it but considering that both are used in a jupyter notebook, it would be convenient to have it installed by default, particularly since notebook v7, only the `ipympl` backend can be used in the notebook.

**Comment by jlaehne** [comment]
@AndrewHerzing see  #58

**Comment by ericpre** [comment]
The package on conda-forge has been dealt with in https://github.com/conda-forge/hyperspy-gui-ipywidgets-feedstock/pull/18.
